# -*- coding: utf-8 -*-
"""Housepricing_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiJdFk0_pCJo8mcln6f31H6UM9HlWBNq
"""

import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from datacleaninghousepricing import clean_data_Housepricing

def run_rf_Housepricing():

    df = clean_data_Housepricing()

    y = df['SalePrice']
    X = df.drop('SalePrice', axis = 1)

    cat_cols = ['Location', 'Basement available', 'Quality',
                'Air Conditioning available']

    num_cols = ['Property Area (ft²)', 'Living Area without Basement (ft²)',
                'Basement Area (ft²)', 'Beds', 'Kitchens', 'Baths',
                'Garage Capacity', 'Year Built',
                'last Renovation (year)']

    preprocessor = ColumnTransformer([
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ], remainder='passthrough')

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('rf', RandomForestRegressor(random_state=42, max_depth= 20,
                                          min_samples_leaf= 1, min_samples_split= 2,
                                          n_estimators = 200))
        ])

    pipeline.fit(X,y)


    return pipeline

import joblib

model = run_rf_Housepricing()
joblib.dump(model, "Housepricing_in_Ames_model.pkl")