# -*- coding: utf-8 -*-
"""Housepricing-Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTuo6hb4Uwbn-r11mTtzDu0654b-eXAA
"""

import sys

sys.path.append("/content")
#I am importing my models
from decisiontree_housepricing import run_dectree_Housepricing
from linear_regression_housepricing import run_linreg_Housepricing
from randomforest_housepricing import run_rf_Housepricing

#I am printing the results of my models and printing my conclusion and decision which model is the best
def main():
    print("\n--- Decision Tree ---")
    metrics = run_dectree_Housepricing()
    print(f"Metriken: {metrics}")


    print("\n--- Linear Regression ---")
    metrics = run_linreg_Housepricing()
    print(f"Metriken: {metrics}")

    print("\n--- Random Forest ---")
    metrics = run_rf_Housepricing()
    print(f"Metriken: {metrics}")

    print("\n--- Conclusion ---")
    print("-> The best model is RandomForest.")
    print("-> The metrics mean absolute error and r2-score are important parameters for deciding on the best model.")
    print("-> The mean absolute error shows the average deviation from the original price.")
    print("-> The r2-score shows how explainable the variance is and how good the model is compared to the mean")
    print("-> RandomForest shows the best metrics with ~18.725€ deviation and a r2-score of ~0,79")
#this safes my Code to run wrong code if I importing it to a other project
if __name__ == "__main__":
    main()